#!/usr/bin/env bun
// tools/release — the GENERATED npm packages. Neither of these is a workspace member and
// neither is ever checked in: `@autono/pinbox` (the ~5 KB launcher) and the four
// `@autono/pinbox-<os>-<cpu>` packages are materialized at release time from this file.
//
// Two deliberate inversions of the house rules live here, both required by the format:
//   1. the launcher shim is plain CommonJS with a `#!/usr/bin/env node` shebang — npm's bin
//      machinery assumes node, so this is packaging glue, not pinbox;
//   2. neither manifest declares `engines` — the binary embeds Bun, and an engines field
//      would block exactly the machines the binary exists to serve.
import { $ } from "bun";
import { TARGETS, type Target } from "./targets.ts";

const REPO_URL = "git+https://github.com/autonoco/pinbox.git";
const HOMEPAGE = "https://github.com/autonoco/pinbox";
const BIN_NAME = "pinbox";

/** The launcher: manifest + the shim it links as `pinbox`. */
export function launcherPackage(version: string): { manifest: object; shimJs: string } {
  const optionalDependencies: Record<string, string> = {};
  // EXACT pins, never a range: a range lets npm resolve a platform package the launcher was
  // not published with, which is a broken install for as long as the window is open.
  for (const target of TARGETS) optionalDependencies[target.pkgName] = version;
  return {
    manifest: {
      name: "@autono/pinbox",
      version,
      description: "CLI-first feedback loop: pins dropped on a live app, fixed by agents.",
      license: "MIT",
      type: "commonjs",
      homepage: HOMEPAGE,
      repository: { type: "git", url: REPO_URL, directory: "packages/cli" },
      bin: { [BIN_NAME]: `bin/${BIN_NAME}.js` },
      files: ["bin"],
      optionalDependencies,
    },
    shimJs: shim(),
  };
}

/** One platform package: one binary, gated by npm's own os/cpu fields. */
export function platformPackage(target: Target, version: string): object {
  return {
    name: target.pkgName,
    version,
    description: `The pinbox binary for ${target.npmOs} ${target.npmCpu}.`,
    license: "MIT",
    homepage: HOMEPAGE,
    repository: { type: "git", url: REPO_URL, directory: "tools/release" },
    os: [target.npmOs],
    cpu: [target.npmCpu],
    // No `bin`: the launcher resolves this binary itself, so npm must not link it.
    files: ["bin"],
  };
}

/** Materialize a platform package (manifest + the compiled binary) under `outDir`. */
export async function stagePlatform(
  target: Target,
  version: string,
  binary: string,
  outDir: string,
): Promise<string> {
  const dir = `${outDir}/${target.npmOs}-${target.npmCpu}`;
  await $`mkdir -p ${dir}/bin`.quiet();
  // `cp` rather than Bun.write: the executable bit is the payload here.
  await $`cp ${binary} ${dir}/bin/${BIN_NAME}`.quiet();
  await $`chmod 755 ${dir}/bin/${BIN_NAME}`.quiet();
  await writeJson(`${dir}/package.json`, platformPackage(target, version));
  await Bun.write(
    `${dir}/README.md`,
    `# ${target.pkgName}\n\nThe pinbox binary for ${target.npmOs} ${target.npmCpu}. ` +
      "Installed automatically as an optional dependency of " +
      `[\`@autono/pinbox\`](${HOMEPAGE}); do not depend on it directly.\n`,
  );
  return dir;
}

/** Materialize the launcher package under `outDir`. */
export async function stageLauncher(version: string, outDir: string): Promise<string> {
  const dir = `${outDir}/launcher`;
  const { manifest, shimJs } = launcherPackage(version);
  await $`mkdir -p ${dir}/bin`.quiet();
  await writeJson(`${dir}/package.json`, manifest);
  await Bun.write(`${dir}/bin/${BIN_NAME}.js`, shimJs);
  await $`chmod 755 ${dir}/bin/${BIN_NAME}.js`.quiet();
  await Bun.write(
    `${dir}/README.md`,
    "# pinbox\n\nCLI-first feedback loop: pins dropped on a live app, fixed and resolved by " +
      `agents.\n\n\`\`\`sh\nnpm install -g @autono/pinbox\npinbox init\n\`\`\`\n\n` +
      `Docs: ${HOMEPAGE}\n`,
  );
  return dir;
}

async function writeJson(path: string, value: object): Promise<void> {
  await Bun.write(path, `${JSON.stringify(value, null, 2)}\n`);
}

function shim(): string {
  const table = TARGETS.map(
    (t) => `  "${t.npmOs}-${t.npmCpu}": ${JSON.stringify(t.pkgName)},`,
  ).join("\n");
  return `#!/usr/bin/env node
// GENERATED by tools/release/manifests.ts — do not edit; edit the generator.
//
// AGENTS.md guest rule, sanctioned exception: this shim is packaging glue, not pinbox. npm
// links it as \`pinbox\` and npm's bin machinery assumes a node shebang, so on nearly every
// machine — Bun-first ones included — this file executes under Node. It therefore uses the
// Node/Bun shared subset only. It declares no \`engines\` either: the binary it spawns embeds
// its own Bun runtime, and an engines field would block the machines that binary serves.
"use strict";

const { spawnSync } = require("node:child_process");
const { dirname, join } = require("node:path");

const PLATFORMS = {
${table}
};

const key = process.platform + "-" + process.arch;
const pkg = PLATFORMS[key];

let binary;
try {
  if (!pkg) throw new Error("unsupported platform " + key);
  // Resolve the MANIFEST, then join to the binary. Package managers disagree about
  // resolving non-JS files (pnpm, yarn PnP, npm workspaces all differ); every one of
  // them resolves a package.json.
  binary = join(dirname(require.resolve(pkg + "/package.json")), "bin", ${JSON.stringify(BIN_NAME)});
} catch {
  console.error(
    "pinbox: no binary found for " + key + ".\\n" +
      "Supported platforms: " + Object.keys(PLATFORMS).join(", ") + ".\\n" +
      "If yours is listed, the optional dependency was skipped at install time — almost\\n" +
      "always --no-optional (or a lockfile/cache produced with it). Reinstall without it:\\n" +
      "  npm install @autono/pinbox\\n" +
      "Or grab the standalone binary: ${HOMEPAGE}/releases",
  );
  process.exit(1);
}

// stdio inherit so the TTY survives: pinbox is interactive and its output is a contract.
const result = spawnSync(binary, process.argv.slice(2), { stdio: "inherit" });

if (result.error) {
  console.error("pinbox: failed to execute " + binary + ": " + result.error.message);
  process.exit(1);
}
// Re-raise the child's signal instead of exiting 0: Ctrl-C must still be 130.
if (result.signal) {
  process.kill(process.pid, result.signal);
  process.exit(1);
}
process.exit(result.status === null ? 1 : result.status);
`;
}
