// GENERATED by tools/skillgen — do not edit; run `bun tools/skillgen/generate.ts`.
// Embedded copy of packages/cli/hooks/post-commit — the compiled binary carries no
// loose files, so `pinbox init` writes THIS into the repo's .git/hooks/.

export const GIT_HOOK_ASSET: { name: string; mode: number; contents: string } = {
  name: "post-commit",
  mode: 0o755,
  contents:
    "#!/bin/sh\n# pinbox git hook — post-commit → `pinbox session trailer` (commit-trailer resolution).\n# Canonical copy: the agent plugins copy this file byte-identical; `pinbox init`'s long-tail\n# path installs it into .git/hooks/. `|| true` on every path: a broken hub must never\n# block a commit. Amend/rebase re-fires are safe — already-resolved and unknown ids\n# skip silently.\nif command -v pinbox >/dev/null 2>&1; then\n  pinbox session trailer || true\nelse\n  bunx @autono/pinbox session trailer || true\nfi\n",
};
