// pinbox CLI — git hook + gitignore installation.
// The post-commit payload is EMBEDDED (git-hook-asset.ts, generated by tools/skillgen from
// packages/cli/hooks/post-commit): `bun build --compile` ships no loose files, so reading
// the payload off disk works only from a source checkout — which is how the hook quietly
// failed to install for every real user once already. A hook the user already has is never
// clobbered.
import { $ } from "bun";
import { GIT_HOOK_ASSET } from "./git-hook-asset.ts";

/** The payload always exists (it is a compiled-in constant), so the only outcomes are:
 * no repo, a hook already there, or written. */
export async function installGitHook(
  projectDir: string,
  opts?: { dryRun?: boolean },
): Promise<"installed" | "kept" | "skipped-no-git"> {
  const hooksDir = gitHooksDir(projectDir);
  if (hooksDir === null) return "skipped-no-git";
  const hookPath = `${hooksDir}/${GIT_HOOK_ASSET.name}`;
  if (await Bun.file(hookPath).exists()) return "kept";
  if (opts?.dryRun === true) return "installed";
  await Bun.write(hookPath, GIT_HOOK_ASSET.contents, { createPath: true });
  await $`chmod ${GIT_HOOK_ASSET.mode.toString(8)} ${hookPath}`.quiet();
  return "installed";
}

/** Idempotently add the `.pinbox/` entry to the project's .gitignore.
 * `dryRun` reports the outcome a real run would produce without touching the file. */
export async function ensureGitignore(
  projectDir: string,
  opts?: { dryRun?: boolean },
): Promise<"appended" | "unchanged" | "created"> {
  const dryRun = opts?.dryRun === true;
  const path = `${projectDir}/.gitignore`;
  const file = Bun.file(path);
  if (!(await file.exists())) {
    if (!dryRun) await Bun.write(path, ".pinbox/\n");
    return "created";
  }
  const existing = await file.text();
  const present = existing
    .split("\n")
    .some((line) => line.trim() === ".pinbox/" || line.trim() === ".pinbox");
  if (present) return "unchanged";
  if (!dryRun) {
    const separator = existing === "" || existing.endsWith("\n") ? "" : "\n";
    await Bun.write(path, `${existing}${separator}.pinbox/\n`);
  }
  return "appended";
}

/**
 * The repo's hooks dir via `git rev-parse --git-path hooks` (handles worktrees, where
 * `.git` is a file); null when the dir is not a git repo or git is unavailable.
 */
function gitHooksDir(projectDir: string): string | null {
  try {
    const result = Bun.spawnSync(["git", "rev-parse", "--git-path", "hooks"], { cwd: projectDir });
    if (!result.success) return null;
    const out = result.stdout.toString().trim();
    if (out === "") return null;
    return out.startsWith("/") ? out : `${projectDir}/${out}`;
  } catch {
    return null;
  }
}
