#!/usr/bin/env bun
// tools/skillgen — generates every derived plugin artifact from the live CLI:
//   · SKILL.md (rendered from buildProgram(); three byte-identical copies)
//   · both plugin manifests (one source: plugin-meta.ts)
//   · plugins/pinbox/hooks/*.sh synced byte-identical from packages/cli/hooks/ (sessions
//     phase is canonical; a missing payload warns rather than fails)
//   · packages/cli/src/init/plugin-assets.ts — embedded copy of plugins/pinbox/** for the
//     compiled binary (`pinbox init`'s @skills-dir route materializes it; no loose files)
//   · packages/cli/src/init/git-hook-asset.ts — embedded packages/cli/hooks/post-commit, for
//     the same reason. This one is REQUIRED, not warned: silently dropping it is how
//     commit-trailer resolution died in every shipped binary once already.
// `bun tools/skillgen/generate.ts` writes; `--check` byte-diffs and exits 1 on drift.
import { $ } from "bun";
import { buildProgram } from "../../packages/cli/src/main.ts";
import { pluginMeta, renderClaudeManifest, renderCodexManifest } from "./plugin-meta.ts";
import { renderSkill } from "./render.ts";

const DEFAULT_ROOT = new URL("../..", import.meta.url).pathname.replace(/\/$/, "");
const PLUGIN_DIR = "plugins/pinbox";
const ASSETS_MODULE = "packages/cli/src/init/plugin-assets.ts";
const GIT_HOOK_MODULE = "packages/cli/src/init/git-hook-asset.ts";
// §8 pinned payload set — the sessions phase authors these; skillgen only copies.
const HOOK_PAYLOADS = ["session-start.sh", "inject.sh", "stop.sh"];
/** The git hook `pinbox init` installs — not a plugin file, so it gets its own module. */
const GIT_HOOK_NAME = "post-commit";
const SKILL_COPIES = [
  "skills/pinbox/SKILL.md",
  `${PLUGIN_DIR}/skills/pinbox/SKILL.md`,
  "integrations/hermes/skills/pinbox/SKILL.md",
];

export type GenerateResult = { wrote: string[]; drifted: string[]; warnings: string[] };

export async function generateAll(opts?: {
  check?: boolean;
  /** Repo root override — tests point this at a mutated copy to exercise drift detection. */
  root?: string;
}): Promise<GenerateResult> {
  const root = opts?.root ?? DEFAULT_ROOT;
  const { outputs, warnings } = await collectOutputs(root);
  const wrote: string[] = [];
  const drifted: string[] = [];
  for (const path of [...outputs.keys()].sort()) {
    const generated = outputs.get(path) as string;
    if (opts?.check) {
      if (generated !== (await checkedInText(`${root}/${path}`))) drifted.push(path);
    } else {
      await Bun.write(`${root}/${path}`, generated);
      wrote.push(path);
    }
  }
  return { wrote, drifted, warnings };
}

/** Render every output in memory: repo-relative path → contents, plus sync warnings. */
async function collectOutputs(
  root: string,
): Promise<{ outputs: Map<string, string>; warnings: string[] }> {
  const packageJson = (await Bun.file(`${root}/packages/cli/package.json`).json()) as {
    version: string;
  };
  const version = packageJson.version;
  const outputs = new Map<string, string>();
  const warnings: string[] = [];

  const skill = renderSkill(buildProgram(), version);
  for (const copy of SKILL_COPIES) outputs.set(copy, skill);

  const meta = pluginMeta(version);
  outputs.set(
    `${PLUGIN_DIR}/.claude-plugin/plugin.json`,
    await biomeFormat("plugin.json", renderClaudeManifest(meta)),
  );
  outputs.set(
    `${PLUGIN_DIR}/.codex-plugin/plugin.json`,
    await biomeFormat("plugin.json", renderCodexManifest(meta)),
  );

  for (const name of HOOK_PAYLOADS) {
    const canonical = Bun.file(`${root}/packages/cli/hooks/${name}`);
    if (await canonical.exists()) {
      outputs.set(`${PLUGIN_DIR}/hooks/${name}`, await canonical.text());
    } else {
      warnings.push(
        `packages/cli/hooks/${name} is missing — ${PLUGIN_DIR}/hooks/${name} not synced`,
      );
    }
  }

  outputs.set(ASSETS_MODULE, await renderAssetsModule(root, outputs));
  outputs.set(GIT_HOOK_MODULE, await renderGitHookModule(root));
  return { outputs, warnings };
}

/**
 * Emit git-hook-asset.ts: the post-commit payload as a string constant, because
 * `bun build --compile` embeds no loose files and `pinbox init` must install the hook from
 * the shipped binary, not from a source checkout. Absence throws — a warning here would
 * reproduce the exact silent failure this module exists to prevent.
 */
async function renderGitHookModule(root: string): Promise<string> {
  const canonical = Bun.file(`${root}/packages/cli/hooks/${GIT_HOOK_NAME}`);
  if (!(await canonical.exists())) {
    throw new Error(
      `packages/cli/hooks/${GIT_HOOK_NAME} is missing — ${GIT_HOOK_MODULE} cannot be ` +
        "generated, and without it `pinbox init` installs no git hook from the binary.",
    );
  }
  const module = [
    "// GENERATED by tools/skillgen — do not edit; run `bun tools/skillgen/generate.ts`.",
    `// Embedded copy of packages/cli/hooks/${GIT_HOOK_NAME} — the compiled binary carries no`,
    "// loose files, so `pinbox init` writes THIS into the repo's .git/hooks/.",
    "",
    "export const GIT_HOOK_ASSET: { name: string; mode: number; contents: string } = {",
    `  name: ${JSON.stringify(GIT_HOOK_NAME)},`,
    "  mode: 0o755,",
    `  contents: ${JSON.stringify(await canonical.text())},`,
    "};",
    "",
  ].join("\n");
  return biomeFormat("git-hook-asset.ts", module);
}

async function checkedInText(path: string): Promise<string | null> {
  const file = Bun.file(path);
  return (await file.exists()) ? await file.text() : null;
}

/**
 * Emit plugin-assets.ts: every file under plugins/pinbox/** (tests excluded — dev gate,
 * not plugin artifact), with this run's generated contents overlaid so the module never
 * lags the outputs written alongside it. Modes are policy, not stat: executables are
 * exactly bin/* and hooks/*.sh.
 */
async function renderAssetsModule(root: string, outputs: Map<string, string>): Promise<string> {
  const pluginRoot = `${root}/${PLUGIN_DIR}`;
  const glob = new Bun.Glob("**/*");
  const paths = new Set(
    (await Array.fromAsync(glob.scan({ cwd: pluginRoot, dot: true }))).filter(
      (path) => !path.endsWith(".test.ts"),
    ),
  );
  for (const key of outputs.keys()) {
    if (key.startsWith(`${PLUGIN_DIR}/`)) paths.add(key.slice(PLUGIN_DIR.length + 1));
  }
  const entries: string[] = [];
  for (const path of [...paths].sort()) {
    const contents =
      outputs.get(`${PLUGIN_DIR}/${path}`) ?? (await Bun.file(`${pluginRoot}/${path}`).text());
    const mode = path.startsWith("bin/") || path.endsWith(".sh") ? 0o755 : 0o644;
    entries.push(
      `  { path: ${JSON.stringify(path)}, mode: 0o${mode.toString(8)}, ` +
        `contents: ${JSON.stringify(contents)} },`,
    );
  }
  const module = [
    "// GENERATED by tools/skillgen — do not edit; run `bun tools/skillgen/generate.ts`.",
    "// Embedded copy of plugins/pinbox/** — the compiled binary carries no loose files, so",
    "// `pinbox init`'s @skills-dir route materializes THIS into <target>/.claude/skills/pinbox/.",
    "// biome-ignore-all lint/suspicious/noTemplateCurlyInString: embedded hooks.json carries" +
      " the literal dual-root shell idiom (" +
      "$" +
      "{CLAUDE_PLUGIN_ROOT:-...} is shell, not a template placeholder)",
    "",
    "export const PLUGIN_FILES: readonly { path: string; mode: number; contents: string }[] = [",
    ...entries,
    "];",
    "",
  ].join("\n");
  return biomeFormat("plugin-assets.ts", module);
}

/** Canonicalize through biome so generated files are `bun run check`-clean by construction. */
async function biomeFormat(virtualName: string, raw: string): Promise<string> {
  const result = await $`bunx biome format --stdin-file-path=${virtualName} < ${new Response(raw)}`
    .cwd(DEFAULT_ROOT)
    .quiet();
  return result.stdout.toString();
}

if (import.meta.main) {
  const check = Bun.argv.includes("--check");
  const result = await generateAll({ check });
  for (const warning of result.warnings) console.error(`warn  ${warning}`);
  if (check) {
    if (result.drifted.length > 0) {
      console.error("skillgen drift — regenerate with `bun tools/skillgen/generate.ts`:");
      for (const path of result.drifted) console.error(`  ${path}`);
      process.exit(1);
    }
    console.error("skillgen: outputs match the command tree");
  } else {
    for (const path of result.wrote) console.log(path);
  }
}
